---
- hosts: all
  pre_tasks:
    - name: Set the stable docker repository
      apt_repository: 
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
        state: present
        update_cache: yes
  become: true
  vars_files:
    - host_vars/vault.yml
  vars:

  roles:
    - angstwad.docker_ubuntu
    - ec3
    - common
