galaxy_info:
  author: Jack Steel (jackodsteel)
  description: A role for a home media server using docker containers

  license: Apache

  min_ansible_version: 2.4

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
  - name: Ubuntu-16.04
  - name: Ubuntu-18.04
  galaxy_tags:
    - 'homelab'
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

