---
- name: Build heimdall
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    pull: true
    state: started
    detach: true
    restart_policy: always
    env:
      PUID: "{{user.PID}}"
      PGID: "{{user.PID}}"
      TZ: CST
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{containers_folder}}/heimdall/config:/config"